"""
AgentState TypedDict definition.

This state structure is shared across all nodes in the LangGraph workflow.
It handles both fast dashboard loads and complex chat queries.
"""

from typing import TypedDict, List, Optional, Dict, Any
from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    """
    Shared state structure for the trading analytics workflow.
    
    This state flows through all nodes in the graph, accumulating data
    as it progresses through the workflow.
    """
    # --- Input ---
    request_type: str                  # "dashboard_load" or "chat_query"
    chat_history: List[BaseMessage]     # MEMORY: Keeps track of conversation
    user_query: Optional[str]          # Current question (only for chat_query)
    
    # --- Classification ---
    target_domain: Optional[str]       # e.g., "Revenue & Monetization", "Risk"
    mapped_insight_id: Optional[int]    # ID 1-18 (e.g., 17 for "Revenue Drop")
    insight_name: Optional[str]         # Human readable name
    
    # --- Data Layer ---
    fetched_data: Dict[str, Any]        # Raw results (empty for PostgreSQL pipeline)
    derived_data: Dict[str, Any]       # MATH RESULTS: Calculated in Python pipeline
    
    # --- Output ---
    root_cause_analysis: Optional[str] # The "Why" narrative generated by LLM
    final_response: Dict[str, Any]     # JSON ready for Frontend rendering
    errors: List[str]                   # Error log
